services:
  postgresdb:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  app:
    container_name: springboot-post
    image: springboot-postgres
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
  # la URL del database va scritta in questo modo dovuta al docker e la porta è quella interna al docker
      DATABASE_URL: postgresql://postgresdb:5432/postgres
